#############################################
# Environment
#############################################

baseUrl=http://172.16.50.43:3088
#core.baseUrl=http://172.16.50.18:8080

#QA_baseUrl=http://172.16.50.18:3088
#stag_baseUrl=http://172.16.50.43:3088

#############################################
# Admin Configuration
#############################################

auth_url=/authenticate-admin
otp_url=/verify-admin-otp

#############################################
# Admin Auth Configuration
#############################################
admin.id=0
#admin.email=ravikiran.j@beamx.co
#admin.password=R@vi@7284
#admin.email=praksh.sahu@amtelkom.com
#admin.password=Amal@123
#admin.deviceType=WEB
#admin.deviceId=************************************
#admin.msisdn=718118948
#admin.userType=ADMIN

#admin.email=abdirahman.buryar@amtelkom.com
#admin.password=Abdirahman@2026
admin.email=info@amtelkom.com
admin.password=QA@2026#
admin.deviceType=WEB
admin.deviceId=postman-live
admin.msisdn=718118948
admin.userType=ADMIN

admin.pinCode=9999
admin.notificationToken=null
admin.otpState=null
admin.submittedById=0
admin.jwttoken=null

#############################################
# Subscriber Configuration
#############################################

subscriber.deviceId=a8f3c9e2-1b4d-4c77-9f21-xyz123
subscriber.deviceType=ANDROID
subscriber.userType=SUBSCRIBER
subscriber.msisdn=+252710000088
subscriber.notificationToken=qa
subscriber.pincode=9999